#!/usr/bin/env python3
"""Generate include/gcu/font.h — a fixed-cell bitmap font for the product.

Rendered from Consolas (monospace, present on Windows dev hosts) at a cell
of 10x18 px, printable ASCII 32..126. Every product string (banner, labels,
digits, title) uses this set; missing glyphs drawing as blocks are a
product defect (spec.md §4.2), so the header is committed, not built on CI.

Layout: FONT_W*FONT_H cells, row-major bits, one glyph = FONT_H rows of
FONT_ROW_BYTES bytes, MSB = leftmost pixel.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT_W, FONT_H = 10, 18
FIRST, LAST = 32, 126
TTF = "C:/Windows/Fonts/consola.ttf"
OUT = Path(__file__).resolve().parent.parent / "include" / "gcu" / "font.h"

ROW_BYTES = (FONT_W + 7) // 8


def main() -> None:
    font = ImageFont.truetype(TTF, 16)
    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("1", (FONT_W, FONT_H), 0)
        d = ImageDraw.Draw(img)
        d.text((0, 1), chr(code), fill=1, font=font)
        glyph = []
        for y in range(FONT_H):
            b = 0
            for x in range(FONT_W):
                if img.getpixel((x, y)):
                    b |= 0x8000 >> x
            for i in range(ROW_BYTES):
                glyph.append((b >> (8 * (1 - i))) & 0xFF)
        rows.append((code, glyph))

    lines = [
        "#ifndef GCU_FONT_H_INCLUDED",
        "#define GCU_FONT_H_INCLUDED",
        "",
        "/* Generated by tools/make_font.py — do not edit by hand. */",
        "",
        f"#define GCU_FONT_W {FONT_W}",
        f"#define GCU_FONT_H {FONT_H}",
        f"#define GCU_FONT_FIRST {FIRST}",
        f"#define GCU_FONT_LAST {LAST}",
        f"#define GCU_FONT_ROW_BYTES {ROW_BYTES}",
        "",
        "static const unsigned char GCU_FONT[][GCU_FONT_H * GCU_FONT_ROW_BYTES] = {",
    ]
    for code, glyph in rows:
        body = ", ".join(str(v) for v in glyph)
        ch = chr(code) if code != 92 else "backslash"
        lines.append(f"    {{{body}}}, /* '{ch}' */")
    lines += ["};", "", "#endif", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({LAST - FIRST + 1} glyphs, {FONT_W}x{FONT_H})")


if __name__ == "__main__":
    main()
